export const Projects = [{
    img:'algo.jpeg',
    img2:'',
    img3:'',
    imgStart:'start',
    topLine: "Algorithm Visulizer",
    headLine: "React",
    lightText: false,
    description: "An Algorithm visulizer that provides in-depth demonstration of most used Pathfinding Algorithms.",
    subtitle: "",
    buttonLabel:"View Site",
    location: "https://jaivalbhup.github.io/AlgorithmVisualizer-React",
    lightBg: true
},
{
    img:'webc.jpg',
    img2:'',
    img3:'',
    imgStart:'',
    topLine: "WebChat",
    headLine: "Django | React | REST Framework",
    lightText: true,
    description: "This is a Chat applications where you can chat with a group of people. You can Create rooms and invite people. I have created my own APIs for this application.",
    subtitle: "",
    buttonLabel:"GitHub",
    location: "https://jaivalbhup.github.io/Django-React-ChatApp",
    lightBg: false
},
{
    img:'hp.png',
    img2:'',
    img3:'',
    imgStart:'start',
    topLine: "House Party",
    headLine: "Django | React | Spotify API | REST Framework",
    lightText: false,
    description: "A fullstack web application that let you collaborate and control the music in a room. It uses soptify API to play, pause and skip the song.",
    subtitle: "",
    buttonLabel:"Github",
    location: "https://github.com/JaivalBhup/HouseParty",
    lightBg: true 
},
{
    img:'btree.svg',
    img2:'',
    img3:'',
    imgStart:'',
    topLine: "Level Order Printing Binary Tree",
    headLine: "C",
    lightText: true,
    description: "An Application that takes a file with a serialized string of a binary tree, deserializes it with PRE-ORDER TRAVARSAL and prints a level ordered Binary tree.",
    subtitle: "",
    buttonLabel:"Github",
    location: "https://github.com/JaivalBhup/LevelOrderBinaryTreePrintingC",
    lightBg: false 
},

{
    img:'stb1.PNG',
    img2:'stb2.PNG', 
    img3:'stb3.PNG',
    imgStart:'start',
    topLine: "SplitTheBill",
    headLine: "Swift | FireBase",
    lightText: false,
    description: "A Bill splitting app that can store events and contributors and can settle up the bill equally between all contributors. Contributors can add bills for the events and the app manages all the bills. Data is stored and fetched from firebase's realtime firestore. It uses firebase authentication. ",
    subtitle: "",
    buttonLabel:"Github",
    location: "https://github.com/JaivalBhup/SplitTheBillApp-iOS-Swift/tree/FireBase",
    lightBg: true 
},
{
    img:'tdl2.jpeg',
    img2:'tdl1.jpeg', 
    img3:'',
    imgStart:'',
    topLine: "ToDoList",
    headLine: "Swift | Realm",
    lightText: true,
    description: "A productivity app to keep track of day to day routine any manage schedule.",
    subtitle: "",
    buttonLabel:"Github",
    location: "https://github.com/JaivalBhup/SplitTheBillApp-iOS-Swift",
    lightBg: false 
}
]
// {
//     img:'python.svg',
//     imgStart:'',
//     topLine: "FlashChat",
//     headLine: "Swift | FireBase",
//     lightText: true,
//     description: "A Chat Application that uses FireBase to store Data",
//     subtitle: "",
//     buttonLabel:"Github",
//     location: "https://github.com/JaivalBhup",
//     lightBg: false 
// },
// {
//     img:'animation.gif',
//     img2:'',
//     img3:'',
//     imgStart:'',
//     topLine: "Project Hunt",
//     headLine: "Python | Django | JavaScript",
//     lightText: true,
//     description: "A Product Hunt clone where an user can post their idea of any project idea or their creation, upvote or downvote other projects and comment on any post.",
//     subtitle: "",
//     buttonLabel:"Github",
//     location: "https://github.com/JaivalBhup/ProjectHuntPython-Django",
//     lightBg: false 
// },