export const Projects = [{
    img:['algo.jpeg'],
    imgStart:'start',
    topLine: "Algorithm Visulizer",
    headLine: "React",
    lightText: false,
    description: "An Algorithm visulizer that provides in-depth demonstration of most used Pathfinding Algorithms.",
    subtitle: "",
    buttonLabel:"View Site",
    location: "https://jaivalbhup.github.io/AlgorithmVisualizer-React",
    lightBg: true
},
{
    img:['webc.jpg'],
    imgStart:'',
    topLine: "WebChat",
    headLine: "Django | React | REST Framework",
    lightText: true,
    description: "This is a Chat applications where you can chat with a group of people. You can Create rooms and invite people. I have created my own APIs for this application.",
    subtitle: "",
    buttonLabel:"GitHub",
    location: "https://jaivalbhup.github.io/Django-React-ChatApp",
    lightBg: false
},
{
    img:['hp.png'],
    imgStart:'start',
    topLine: "House Party",
    headLine: "Django | React | Spotify API | REST Framework",
    lightText: false,
    description: "A fullstack web application that let you collaborate and control the music in a room. It uses soptify API to play, pause and skip the song.",
    subtitle: "",
    buttonLabel:"Github",
    location: "https://github.com/JaivalBhup/HouseParty",
    lightBg: true 
},
{
    img:['fc1.PNG','fc2.PNG','fc3.PNG'],
    imgStart:'',
    topLine: "Flash Checkout",
    headLine: "Swift | Firebase",
    lightText: true,
    description: "This application is an solution to the Future of retail challenge. This application can make your shopping experience as easy as making a bread. No need of waiting in long lines of checkout just scan the item directly from the shelf and pay on the go.",
    subtitle: "",
    buttonLabel:"Github",
    location: "https://github.com/JaivalBhup/FlashCheckout",
    lightBg: false 
},

{
    img:['stb1.PNG','stb2.PNG', 'stb3.PNG'],
    imgStart:'start',
    topLine: "SplitTheBill",
    headLine: "Swift | FireBase",
    lightText: false,
    description: "A Bill splitting app that can store events and contributors and can settle up the bill equally between all contributors. Contributors can add bills for the events and the app manages all the bills. Data is stored and fetched from firebase's realtime firestore. It uses firebase authentication. ",
    subtitle: "",
    buttonLabel:"Github",
    location: "https://github.com/JaivalBhup/SplitTheBillApp-iOS-Swift/tree/FireBase",
    lightBg: true 
},
{
    img:['tdl2.jpeg','tdl1.jpeg'],
    imgStart:'',
    topLine: "ToDoList",
    headLine: "Swift | Realm",
    lightText: true,
    description: "A productivity app to keep track of day to day routine any manage schedule.",
    subtitle: "",
    buttonLabel:"Github",
    location: "https://github.com/JaivalBhup/SplitTheBillApp-iOS-Swift",
    lightBg: false 
}
]
// {
//     img:'python.svg',
//     imgStart:'',
//     topLine: "FlashChat",
//     headLine: "Swift | FireBase",
//     lightText: true,
//     description: "A Chat Application that uses FireBase to store Data",
//     subtitle: "",
//     buttonLabel:"Github",
//     location: "https://github.com/JaivalBhup",
//     lightBg: false 
// },
// {
//     img:'animation.gif',
//     img2:'',
//     img3:'',
//     imgStart:'',
//     topLine: "Project Hunt",
//     headLine: "Python | Django | JavaScript",
//     lightText: true,
//     description: "A Product Hunt clone where an user can post their idea of any project idea or their creation, upvote or downvote other projects and comment on any post.",
//     subtitle: "",
//     buttonLabel:"Github",
//     location: "https://github.com/JaivalBhup/ProjectHuntPython-Django",
//     lightBg: false 
// },